# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=0.8.4
maven_group=xyz.nucleoid
archives_base_name=fantasy

# Dependencies
fabric_api_version=0.160.5+26.3
